using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI; //ï¿½pï¿½lï¿½ï¿½ï¿½ÌƒCï¿½ï¿½ï¿½[ï¿½Wï¿½ğ‘€ì‚·ï¿½ï¿½Ì‚É•Kï¿½v
using UnityEngine.SceneManagement;

public class Home : MonoBehaviour
{

	public float fadeSpeed = 0.003f;        //ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½Ï‚ï¿½ï¿½Xï¿½sï¿½[ï¿½hï¿½ï¿½ï¿½Ç—ï¿½
	float red, green, blue, alfa;   //ï¿½pï¿½lï¿½ï¿½ï¿½ÌFï¿½Aï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½Ç—ï¿½
	[HideInInspector]
	public bool onof = false;
	[HideInInspector]
	public bool isFadeOut = false;  //ï¿½tï¿½Fï¿½[ï¿½hï¿½Aï¿½Eï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ÌŠJï¿½nï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç—ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
	[HideInInspector]
	public bool isFadeIn = false;   //ï¿½tï¿½Fï¿½[ï¿½hï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌŠJï¿½nï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç—ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O

	Image fadeImage;                //ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ÏXï¿½ï¿½ï¿½ï¿½pï¿½lï¿½ï¿½ï¿½ÌƒCï¿½ï¿½ï¿½[ï¿½W

	void Start()
	{
		fadeImage = GetComponent<Image>();
		red = fadeImage.color.r;
		green = fadeImage.color.g;
		blue = fadeImage.color.b;
		alfa = fadeImage.color.a;
	}

	void Update()
	{
		if (Input.GetMouseButtonDown(0))
		{
			isFadeOut = true;
			//GeneralManager.Instance.soundManager.PlaySE(SoundManager.SeName.se_02);
		}
		//if (onof == true)
		//{
		//	ChengeNextStageScene();
		//}
		if (isFadeIn)
		{
			StartFadeIn();
		}

		if (isFadeOut)
		{
			StartFadeOut();
		}
	}

	void StartFadeIn()
	{
		alfa -= fadeSpeed;                //a)ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½
		SetAlpha();                      //b)ï¿½ÏXï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½pï¿½lï¿½ï¿½ï¿½É”ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½
		if (alfa <= 0)
		{                    //c)ï¿½ï¿½ï¿½Sï¿½É“ï¿½ï¿½ï¿½ï¿½É‚È‚ï¿½ï¿½ï¿½ï¿½çˆï¿½ï¿½ï¿½ğ”²‚ï¿½ï¿½ï¿½
			isFadeIn = false;
			fadeImage.enabled = false;//d)ï¿½pï¿½lï¿½ï¿½ï¿½Ì•\ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½tï¿½É‚ï¿½ï¿½ï¿½
		}
	}

	void StartFadeOut()
	{
		fadeImage.enabled = true;  // a)ï¿½pï¿½lï¿½ï¿½ï¿½Ì•\ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
		alfa += fadeSpeed;         // b)ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½É‚ï¿½ï¿½ï¿½ï¿½ï¿½
		SetAlpha();               // c)ï¿½ÏXï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½pï¿½lï¿½ï¿½ï¿½É”ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½
		if (alfa >= 1)
		{             // d)ï¿½ï¿½ï¿½Sï¿½É•sï¿½ï¿½ï¿½ï¿½ï¿½É‚È‚ï¿½ï¿½ï¿½ï¿½çˆï¿½ï¿½ï¿½ğ”²‚ï¿½ï¿½ï¿½
			isFadeOut = false;
			onof = true;
		}
	}

	void SetAlpha()
	{
		fadeImage.color = new Color(red, green, blue, alfa);
	}
	
	public void ChengeNextStageScene()
    {
	    GeneralManager.Instance.soundManager.PlaySE(SoundManager.SeName.se_09);
		GeneralManager.Instance.soundManager.StopBGM();
		GeneralManager.Instance.selectStageNum++;
		if (GeneralManager.Instance.selectStageNum > 10)
        {
			SceneManager.LoadScene("SelectStageScene");
		}
        else
        {
			SceneManager.LoadScene("GameScene");
		}

	}
}